### ISSUE TITLE
TODO: serve the static files with Nginx and reverse proxy to flask

### ISSUE THREAD

**Issue by FeynmanDNA** [FeynmanDNA/MakeTheWorldABetterPlace#2]
also need to find out if index.html should be served by Nginx, and debug favicon not showing up

**Comment by kitsune-tanuki** [comment]
在 2018-06-22 21:16:11，"KYY" <notifications@github.com> 写道：


also need to find out if index.html should be served by Nginx, and debug favicon not showing up

**Comment by kitsune-tanuki** [comment]
![default](https://user-images.githubusercontent.com/38519861/41986672-63553d00-7a69-11e8-8246-16de196845e6.jpg)
![default](https://user-images.githubusercontent.com/38519861/41986685-6d9f1e02-7a69-11e8-8aa1-9d94303ed067.jpg)

**Comment by FeynmanDNA** [comment]
00c7b1d6bf48e24f7906fade1d908d7634bce3c1
