### ISSUE TITLE
SUGGESTION: auto step-size

### ISSUE THREAD

**Issue by FeynmanDNA** [FeynmanDNA/MakeTheWorldABetterPlace#3]
maybe a button to auto-correct the step size to fit the 100 items would be good

**Comment by FeynmanDNA** [comment]
autofit

otherwise there's the manual effort of selecting the right step size

**Comment by ghost** [comment]
🐫

iPhoneから送信

2018/07/06 20:35、KYY <notifications@github.com> のメッセージ:

**Comment by FeynmanDNA** [comment]
2ce678a37ea598f635e7a4a60c4df0412395c623
